"""
response_parser.py
------------------
Parse and validate IBM Granite text responses into structured sections.

Responsibilities
----------------
- Extract the four mandatory sections from every Granite response:
    SUMMARY, ROOT CAUSE ANALYSIS, RECOMMENDATIONS, TECHNICAL NOTES
- Validate that each section is present and non-empty.
- Normalise whitespace and strip artefacts.
- Return a typed ParsedGraniteResponse dataclass.
- Provide a safe fallback when Granite is unavailable or the response
  cannot be parsed — callers always receive a usable object.

Section extraction strategy
---------------------------
Headers are matched case-insensitively with a flexible regex that allows
for slight Granite formatting variations. The extractor captures everything
between one header and the next (or end of string).

Architecture constraint
-----------------------
This module only processes text. It has zero knowledge of DSP values,
rule engine logic, or reliability scores. All engineering correctness
was established before Granite was called.

Dependencies: re, dataclasses, logging (all stdlib)
"""

import logging
import re
from dataclasses import dataclass, field
from typing import Optional
logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Section header patterns (order matters for extraction)
# ─────────────────────────────────────────────────────────────────────────────
_SECTION_PATTERNS: list[tuple[str, str]] = [
    ("summary",              r"SUMMARY\s*:"),
    ("root_cause_analysis",  r"ROOT\s+CAUSE\s+ANALYSIS\s*:"),
    ("recommendations",      r"RECOMMENDATIONS\s*:"),
    ("technical_notes",      r"TECHNICAL\s+NOTES\s*:"),
]

# Compiled combined pattern for splitting
_ALL_HEADERS_RE = re.compile(
    r"(?:SUMMARY|ROOT\s+CAUSE\s+ANALYSIS|RECOMMENDATIONS|TECHNICAL\s+NOTES)\s*:",
    re.IGNORECASE,
)

# Numbered list item — used to parse recommendations into a list
_LIST_ITEM_RE = re.compile(r"^\s*(\d+[\.\)]|[-•*])\s+", re.MULTILINE)

# Minimum acceptable character count per section
_MIN_SECTION_LENGTH = 20


# ─────────────────────────────────────────────────────────────────────────────
# Typed result
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class ParsedGraniteResponse:
    """
    Structured representation of a Granite response.

    Attributes
    ----------
    available           : True if Granite responded and was parsed successfully
    summary             : 2-3 sentence overall condition summary
    root_cause_analysis : 3-5 sentence engineering root cause explanation
    recommendations     : list of actionable recommendation strings
    technical_notes     : additional context / caveats
    raw_text            : original Granite response text (for debugging)
    parse_warnings      : list of warning strings if sections were missing/short
    model_id            : Granite model identifier used
    input_tokens        : prompt token count
    output_tokens       : response token count
    latency_ms          : API round-trip in milliseconds
    """
    available:            bool
    summary:              str
    root_cause_analysis:  str
    recommendations:      list[str]
    technical_notes:      str
    raw_text:             str            = field(repr=False)
    parse_warnings:       list[str]      = field(default_factory=list)
    model_id:             str            = ""
    input_tokens:         int            = 0
    output_tokens:        int            = 0
    latency_ms:           int            = 0


# ─────────────────────────────────────────────────────────────────────────────
# Fallback response — returned when Granite is unavailable
# ─────────────────────────────────────────────────────────────────────────────
def _unavailable_response(reason: str, raw: str = "") -> ParsedGraniteResponse:
    """Return a graceful fallback when Granite cannot be reached or parsed."""
    return ParsedGraniteResponse(
        available=False,
        summary=(
            "IBM Granite AI explanation is currently unavailable. "
            "All engineering diagnostics, rule evaluations, and the Circuit "
            "Reliability Score were computed by the deterministic engineering engines "
            "and remain fully valid without AI explanation."
        ),
        root_cause_analysis=(
            "The root cause analysis was performed by the Rule-Based Circuit "
            "Diagnostic Engine. Please refer to the Triggered Rules section "
            "for the complete engineering root cause determination."
        ),
        recommendations=(
            [
                "Refer to the Corrective Actions section generated by the Rule Engine.",
                "All recommendations in the diagnostic report are engineering-validated.",
            ]
        ),
        technical_notes=f"AI explanation unavailable: {reason}",
        raw_text=raw,
        parse_warnings=[f"Unavailable: {reason}"],
    )


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────
def parse_response(granite_response: Any) -> ParsedGraniteResponse:
    """
    Parse a GraniteResponse into a structured ParsedGraniteResponse.

    Accepts either a GraniteResponse dataclass or any duck-typed object
    with the same attributes (available, text, error_message, …).

    Parameters
    ----------
    granite_response : GraniteResponse from granite_client.generate(),
                       or any object with .available, .text, .error_message

    Returns
    -------
    ParsedGraniteResponse — always valid, never raises
    """
    if granite_response is None:
        return _unavailable_response("None response object")

    if not getattr(granite_response, "available", False):
        return _unavailable_response(
            getattr(granite_response, "error_message", "Unknown error"),
            raw=getattr(granite_response, "text", ""),
        )

    raw_text = granite_response.text
    if not raw_text or not raw_text.strip():
        return _unavailable_response("Empty response text", raw=raw_text)

    warnings: list[str] = []

    # ── Extract sections ─────────────────────────────────────────────────────
    sections = _extract_sections(raw_text)

    summary             = _clean(sections.get("summary", ""))
    root_cause_analysis = _clean(sections.get("root_cause_analysis", ""))
    recommendations_raw = _clean(sections.get("recommendations", ""))
    technical_notes     = _clean(sections.get("technical_notes", ""))

    # ── Validate sections ─────────────────────────────────────────────────────
    for name, value in [
        ("SUMMARY",             summary),
        ("ROOT CAUSE ANALYSIS", root_cause_analysis),
        ("RECOMMENDATIONS",     recommendations_raw),
        ("TECHNICAL NOTES",     technical_notes),
    ]:
        if not value:
            warnings.append(f"Section '{name}' missing from response")
            logger.warning("Granite response missing section: %s", name)
        elif len(value) < _MIN_SECTION_LENGTH:
            warnings.append(f"Section '{name}' is suspiciously short ({len(value)} chars)")

    # ── Parse recommendations into list ──────────────────────────────────────
    recommendations = _parse_recommendations(recommendations_raw)

    # ── Fallback: if too many sections missing, use raw text ─────────────────
    critical_missing = sum(
        1 for v in [summary, root_cause_analysis, recommendations_raw] if not v
    )
    if critical_missing >= 2:
        warnings.append("Multiple critical sections missing; using raw response as summary")
        summary = raw_text[:600].strip()
        logger.warning("Granite response poorly structured; %d sections missing", critical_missing)

    parsed = ParsedGraniteResponse(
        available=True,
        summary=summary or "No summary provided.",
        root_cause_analysis=root_cause_analysis or "No root cause analysis provided.",
        recommendations=recommendations or ["No specific recommendations provided."],
        technical_notes=technical_notes or "No technical notes provided.",
        raw_text=raw_text,
        parse_warnings=warnings,
        model_id=getattr(granite_response, "model_id", ""),
        input_tokens=getattr(granite_response, "input_tokens", 0),
        output_tokens=getattr(granite_response, "output_tokens", 0),
        latency_ms=getattr(granite_response, "latency_ms", 0),
    )

    logger.info(
        "Parsed Granite response: %d chars raw, %d recommendations, %d warnings",
        len(raw_text), len(recommendations), len(warnings),
    )
    return parsed


def parse_raw_text(raw_text: str, model_id: str = "") -> ParsedGraniteResponse:
    """
    Parse a plain text string directly (useful for testing without a live API).

    Parameters
    ----------
    raw_text : the Granite-generated text string
    model_id : optional model identifier for metadata

    Returns
    -------
    ParsedGraniteResponse
    """
    # Duck-type a minimal object
    class _MockResponse:
        available     = True
        text          = raw_text
        error_message = ""
        input_tokens  = 0
        output_tokens = 0
        latency_ms    = 0

    _MockResponse.model_id = model_id
    return parse_response(_MockResponse())


# ─────────────────────────────────────────────────────────────────────────────
# Internal: section extractor
# ─────────────────────────────────────────────────────────────────────────────
def _extract_sections(text: str) -> dict[str, str]:
    """
    Split text into named sections using the known header patterns.

    Strategy
    --------
    1. Find all header positions in the text using _ALL_HEADERS_RE.
    2. For each header, extract text between it and the next header (or EOF).
    3. Map the extracted text to the canonical section key.
    """
    result: dict[str, str] = {}

    # Find all header matches with their positions
    matches = list(_ALL_HEADERS_RE.finditer(text))
    if not matches:
        # No structured sections found — treat entire text as summary
        logger.debug("No structured sections found in Granite response")
        return {"summary": text.strip()}

    for i, match in enumerate(matches):
        header_raw  = match.group(0)
        content_start = match.end()
        content_end   = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        content       = text[content_start:content_end].strip()

        # Map the raw header to a canonical key
        key = _header_to_key(header_raw)
        if key:
            result[key] = content

    return result


def _header_to_key(header: str) -> Optional[str]:
    """Map a raw header string to the canonical section key."""
    h = header.upper().replace(":", "").strip()
    if "SUMMARY" in h:
        return "summary"
    if "ROOT" in h and "CAUSE" in h:
        return "root_cause_analysis"
    if "RECOMMENDATION" in h:
        return "recommendations"
    if "TECHNICAL" in h and "NOTE" in h:
        return "technical_notes"
    return None


def _clean(text: str) -> str:
    """Normalise whitespace and strip markdown artefacts."""
    if not text:
        return ""
    # Remove markdown bold/italic markers
    text = re.sub(r"\*{1,3}(.*?)\*{1,3}", r"\1", text)
    # Remove markdown headers
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Collapse multiple blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    # Strip leading/trailing whitespace
    return text.strip()


def _parse_recommendations(text: str) -> list[str]:
    """
    Split a recommendations block into individual items.

    Handles:
    - Numbered lists:  "1. Reduce gain"  /  "1) Reduce gain"
    - Bullet lists:    "- Reduce gain"   /  "• Reduce gain"
    - Plain paragraphs (newline-separated) if no list markers found
    """
    if not text:
        return []

    # Try splitting on list markers first
    items = _LIST_ITEM_RE.split(text)
    # _LIST_ITEM_RE.split returns [pre-text, sep1, item1, sep2, item2, ...]
    # The actual content items are at odd indices >= 2 (after the separator matches)
    # More reliable: use findall to get positions, then slice
    parts = re.split(r"\n\s*(?=\d+[\.\)]|[-•*]\s)", text)
    cleaned = []
    for part in parts:
        # Strip the leading list marker from each part
        part = re.sub(r"^\s*\d+[\.\)]\s*", "", part)
        part = re.sub(r"^\s*[-•*]\s*", "", part)
        part = part.strip()
        if part and len(part) >= 10:
            cleaned.append(part)

    if not cleaned:
        # Fall back to paragraph splitting
        cleaned = [p.strip() for p in text.split("\n\n") if len(p.strip()) >= 10]

    if not cleaned and text.strip():
        cleaned = [text.strip()]

    return cleaned[:8]   # cap at 8 recommendations


# ─────────────────────────────────────────────────────────────────────────────
# Type hint workaround for Any (avoid importing typing in conditional block)
# ─────────────────────────────────────────────────────────────────────────────
from typing import Any  # noqa: E402 — re-import for use in parse_response signature
